- name: ensure required pip-packages are installed
  hosts: localhost

- hosts: all
  roles:
    - name: configure_os
    - name: install_openvpn

  handlers:
    - name: Restart SSH daemon
      service:
        name: sshd
        state: restarted
